services:
  db:
    image: postgres:15-alpine
    container_name: my_postgres_db_dev
    restart: always
    environment:
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: docker_password
      POSTGRES_DB: docker_db
    ports:
      - "5432:5432" # Expose to host for direct DB access if needed
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker_user -d docker_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_api_dev
    restart: unless-stopped
    ports:
      - "3002:3002"
      - "9229:9229" # Node.js debug port (host:container)
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Wait for the DB to be healthy before starting API
    volumes:
      - ./src:/usr/src/app/src
      - ./openapi:/usr/src/app/openapi
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./drizzle.config.ts:/usr/src/app/drizzle.config.ts
    command: sh -c "npm run dev"

volumes:
  pgdata_dev: # Defines the named volume for PostgreSQL data persistence in dev